#ifndef BALL_BALANCE_CONFIG_H
#define BALL_BALANCE_CONFIG_H

#include "ml_board.h"

#ifndef BALL_BALANCE_ALLOW_SEQUENCE
#define BALL_BALANCE_ALLOW_SEQUENCE       (1)
#endif

#ifndef BALL_SEQUENCE_BREAKAWAY_ENABLED
#define BALL_SEQUENCE_BREAKAWAY_ENABLED   (1)
#endif

#ifndef BALL_SEQUENCE_BREAKAWAY_IMMEDIATE_MAXIMUM
#define BALL_SEQUENCE_BREAKAWAY_IMMEDIATE_MAXIMUM (1)
#endif

#ifndef BALL_SEQUENCE_OVERSPEED_BRAKE_ENABLED
#define BALL_SEQUENCE_OVERSPEED_BRAKE_ENABLED (0)
#endif

#if (BALL_SEQUENCE_BREAKAWAY_ENABLED != 0) && \
    (BALL_SEQUENCE_BREAKAWAY_ENABLED != 1)
#error BALL_SEQUENCE_BREAKAWAY_ENABLED must be 0 or 1
#endif

#if (BALL_SEQUENCE_BREAKAWAY_IMMEDIATE_MAXIMUM != 0) && \
    (BALL_SEQUENCE_BREAKAWAY_IMMEDIATE_MAXIMUM != 1)
#error BALL_SEQUENCE_BREAKAWAY_IMMEDIATE_MAXIMUM must be 0 or 1
#endif

#if (BALL_SEQUENCE_OVERSPEED_BRAKE_ENABLED != 0) && \
    (BALL_SEQUENCE_OVERSPEED_BRAKE_ENABLED != 1)
#error BALL_SEQUENCE_OVERSPEED_BRAKE_ENABLED must be 0 or 1
#endif

#define BALL_AUTO_CONTROL_DISABLED         (0)
#define BALL_AUTO_CONTROL_SPEED_TEST       (1)
#define BALL_AUTO_CONTROL_CENTER_LOOP      (2)

#ifndef BALL_AUTO_CONTROL_MODE
#define BALL_AUTO_CONTROL_MODE            BALL_AUTO_CONTROL_DISABLED
#endif

#if (BALL_AUTO_CONTROL_MODE < BALL_AUTO_CONTROL_DISABLED) || \
    (BALL_AUTO_CONTROL_MODE > BALL_AUTO_CONTROL_CENTER_LOOP)
#error BALL_AUTO_CONTROL_MODE is invalid
#endif

/* Dedicated H3 resources. Values below remain unverified until bench tests. */
#define BALL_VISION_UART                  UART2
#define BALL_VISION_UART_BAUD             (115200UL)
#define BALL_VISION_UART_PRIORITY         (1U)
#define BALL_SERVO_TIMER                  TIMA1
#define BALL_SERVO_CHANNEL                DL_TIMER_CC_1_INDEX
#define BALL_TIMEBASE_TIMER               TIMG6
#define BALL_TIMEBASE_PRIORITY            (2U)

#define BALL_SERVO_FREQUENCY_HZ           (50U)
#define BALL_SERVO_MINIMUM_US             (1300U)
#define BALL_SERVO_CENTER_US              (1500U)
#define BALL_SERVO_MAXIMUM_US             (1700U)
#define BALL_SERVO_MAX_SLEW_US_PER_S      (2000UL)
#define BALL_MANUAL_MAX_OFFSET_US         (100)
#define BALL_CALIBRATION_SPEED_TEST       (1)

/* Verified 2026-07-30: 1450 us lowers the +cm side. */
#define BALL_CONTROL_DIRECTION            (-1.0f)

#define BALL_MEASUREMENT_MINIMUM_CM       (-12.5f)
#define BALL_MEASUREMENT_MAXIMUM_CM       (12.5f)

#define BALL_MINIMUM_SCORE                (0.20f)
#define BALL_VISION_TIMEOUT_MS            (150U)
#define BALL_REACQUIRE_FRAME_COUNT        (3U)
#define BALL_MAX_CAPTURE_INTERVAL_MS      (250U)
#define BALL_MAX_OBSERVER_RESIDUAL_CM     (4.0f)
#define BALL_OBSERVER_ALPHA               (0.65f)
#define BALL_OBSERVER_BETA                (0.12f)

/* Unverified cascaded controller starting values. Tune one class at a time. */
#define BALL_CONTROL_PERIOD_MS            (10U)
#define BALL_POSITION_KP_PER_S            (0.8f)
#define BALL_POSITION_KD                  (0.40f)
#define BALL_POSITION_KI_PER_S2           (0.30f)
#define BALL_POSITION_INTEGRAL_LIMIT_CM_S (12.0f)
#define BALL_POSITION_INTEGRAL_SEPARATION_CM (3.0f)
#define BALL_SPEED_REFERENCE_LIMIT_CM_PER_S  (10.0f)
#define BALL_SPEED_KP_US_PER_CM_PER_S     (27.0f)
#define BALL_SPEED_KD_US_PER_CM_PER_S2    (3.0f)
#define BALL_SEQUENCE_SPEED_KD_US_PER_CM_PER_S2 (0.0f)
#define BALL_SPEED_D_FILTER_ALPHA         (0.20f)
#define BALL_CONTROL_LIMIT_US             (200.0f)
#define BALL_SEQUENCE_CRUISE_SPEED_CM_PER_S (4.5f)
#define BALL_SEQUENCE_BRAKE_ACCEL_CM_PER_S2 (18.0f)
#define BALL_SEQUENCE_BRAKE_MARGIN_CM     (0.25f)
#define BALL_SEQUENCE_APPROACH_KP_PER_S   (2.0f)
#define BALL_SEQUENCE_MINUS_CRUISE_SPEED_CM_PER_S (5.0f)
#define BALL_SEQUENCE_MINUS_BRAKE_ACCEL_CM_PER_S2 (20.0f)
#define BALL_SEQUENCE_MINUS_BRAKE_MARGIN_CM (0.30f)
#define BALL_SEQUENCE_MINUS_APPROACH_KP_PER_S (2.0f)
#define BALL_SEQUENCE_MINUS_APPROACH_SPEED_LIMIT_CM_PER_S (4.0f)
#define BALL_SEQUENCE_MINUS_CAPTURE_ERROR_CM (0.80f)
#define BALL_SEQUENCE_MINUS_CAPTURE_KP_PER_S (2.0f)
#define BALL_SEQUENCE_MINUS_RECOVERY_SPEED_LIMIT_CM_PER_S (2.0f)
#define BALL_SEQUENCE_MINUS_CRUISE_BRAKE_LIMIT_US (20.0f)
#define BALL_SEQUENCE_MINUS_BRAKE_SPEED_KD_US_PER_CM_PER_S2 (3.0f)
#define BALL_BREAKAWAY_ERROR_MINIMUM_CM   (0.9f)
#define BALL_BREAKAWAY_STATIONARY_SPEED_MAX_CM_PER_S (0.3f)
#define BALL_SEQUENCE_MINUS_BREAKAWAY_ARM_SPEED_MAX_CM_PER_S (1.0f)
#define BALL_BREAKAWAY_RELEASE_SPEED_CM_PER_S (0.5f)
#define BALL_BREAKAWAY_RELEASE_DISPLACEMENT_CM (0.15f)
#define BALL_BREAKAWAY_AWAY_DISPLACEMENT_CM (0.15f)
#define BALL_BREAKAWAY_RELEASE_CONFIRM_MS (60U)
#define BALL_SEQUENCE_BREAKAWAY_RELEASE_CONFIRM_MS (30U)
#define BALL_BREAKAWAY_ARM_MS             (300U)
#define BALL_SEQUENCE_MINUS_BREAKAWAY_ARM_MS (100U)
#define BALL_SEQUENCE_BREAKAWAY_ARM_PROGRESS_CM (0.15f)
#define BALL_BREAKAWAY_RAMP_US_PER_S      (50.0f)
#define BALL_SEQUENCE_BREAKAWAY_RAMP_US_PER_S (100.0f)
#define BALL_BREAKAWAY_MAXIMUM_US         (150.0f)
#define BALL_BREAKAWAY_MAXIMUM_HOLD_MS    (500U)
#define BALL_BREAKAWAY_SERVO_MINIMUM_US   (1400U)
#define BALL_SEQUENCE_BREAKAWAY_STAGE1_SERVO_MINIMUM_US (1300U)
#define BALL_SEQUENCE_BREAKAWAY_SERVO_MINIMUM_US (1300U)
#define BALL_SEQUENCE_BREAKAWAY_STAGE1_HOLD_MS (250U)
#define BALL_SEQUENCE_BREAKAWAY_STAGE2_HOLD_MS (250U)
#define BALL_BREAKAWAY_SERVO_MAXIMUM_US   (1650U)
#define BALL_SEQUENCE_BRAKE_ENTER_MARGIN_CM_PER_S (0.5f)
#define BALL_SEQUENCE_BRAKE_EXIT_MARGIN_CM_PER_S (0.1f)
#define BALL_TARGET_MINIMUM_CM            (-11.5f)
#define BALL_TARGET_MAXIMUM_CM            (11.5f)

#define BALL_SEQUENCE_PLUS_CM             (5.0f)
#define BALL_SEQUENCE_MINUS_CM            (-5.0f)
#define BALL_SEQUENCE_PLUS_ERROR_CM       (1.0f)
#define BALL_SEQUENCE_FINAL_ERROR_CM      (1.0f)
#define BALL_SEQUENCE_SETTLE_SPEED_MAX_CM_PER_S (1.0f)
#define BALL_SEQUENCE_PLUS_CONFIRM_MS     (30U)
#define BALL_SEQUENCE_FINAL_SETTLE_MS     (500U)
#define BALL_SEQUENCE_TIMEOUT_MS          (5000U)

#if (BALL_SERVO_MINIMUM_US < 1300U) || \
    (BALL_SERVO_MAXIMUM_US > 1700U)
#error Ball servo absolute range must remain within 1300 to 1700 us
#endif

#if (BALL_SEQUENCE_BREAKAWAY_SERVO_MINIMUM_US < \
     BALL_SERVO_MINIMUM_US) || \
    (BALL_BREAKAWAY_SERVO_MAXIMUM_US > BALL_SERVO_MAXIMUM_US)
#error Ball breakaway range must remain inside the servo absolute range
#endif

#if (BALL_SEQUENCE_BREAKAWAY_STAGE1_SERVO_MINIMUM_US < 1300U) || \
    (BALL_SEQUENCE_BREAKAWAY_STAGE1_SERVO_MINIMUM_US > \
     BALL_SERVO_CENTER_US)
#error Ball sequence stage 1 must remain within 1300 us and center
#endif

#endif
